version: '3.8'
services:

  # ===== MICROSERVICES LAYER =====
  content-processor:
    build: 
      context: ${MICROSERVICES_PATH}/content-processor
      dockerfile: Dockerfile
    container_name: learning-content-processor
    ports:
      - "${CONTENT_PROCESSOR_PORT}:${CONTENT_PROCESSOR_PORT}"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ${MICROSERVICES_PATH}/content-processor/src:/app/src
      - ${MICROSERVICES_PATH}/content-processor/.env:/app/.env
      - ${MICROSERVICES_PATH}/content-processor/uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
    networks:
      - learning-network
    restart: unless-stopped

  quiz-generator:
    build: 
      context: ${MICROSERVICES_PATH}/quiz-generator
      dockerfile: Dockerfile
    container_name: learning-quiz-generator
    ports:
      - "${QUIZ_GENERATOR_PORT}:${QUIZ_GENERATOR_PORT}"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ${MICROSERVICES_PATH}/quiz-generator/src:/app/src
      - ${MICROSERVICES_PATH}/quiz-generator/.env:/app/.env
    depends_on:
      - mongodb
      - redis
    networks:
      - learning-network
    restart: unless-stopped

  quiz-engine:
    build: 
      context: ${MICROSERVICES_PATH}/quiz-engine
      dockerfile: Dockerfile
    container_name: learning-quiz-engine
    ports:
      - "${QUIZ_ENGINE_PORT}:${QUIZ_ENGINE_PORT}"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
      - QUIZ_GENERATOR_URL=http://quiz-generator:${QUIZ_GENERATOR_PORT}
    volumes:
      - ${MICROSERVICES_PATH}/quiz-engine/src:/app/src
      - ${MICROSERVICES_PATH}/quiz-engine/.env:/app/.env
    depends_on:
      - mongodb
      - redis
      - quiz-generator
    networks:
      - learning-network
    restart: unless-stopped

